<a href="https://colab.research.google.com/github/KwwwXue/pytorch/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
a = torch.exp(torch.arange(0,20,2))

In [ ]:
a.shape

torch.Size([10])

In [2]:
import numpy as np

In [ ]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
a = a.reshape(4,3,2)

In [ ]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [ ]:
a = torch.ones(5,3)

In [ ]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a.shape

torch.Size([5, 3])

In [ ]:
a = np.array([2,3])
torch.from_numpy(a)

tensor([2, 3])

In [ ]:
b = np.ones([2,3])
torch.from_numpy(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [ ]:
c = torch.Tensor(2,3)
c

tensor([[1.1520e-34, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [ ]:
torch.rand(2,3)

tensor([[0.8063, 0.1756, 0.4381],
        [0.8631, 0.6926, 0.3254]])

In [ ]:
torch.randint(1,10,[2,3])

tensor([[1, 5, 2],
        [3, 9, 1]])

In [ ]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.full([2,3],5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [ ]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [ ]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [ ]:
a = torch.rand(4,1,6,6)
a[0].shape

torch.Size([1, 6, 6])

In [ ]:
a[:2, : ,].shape

torch.Size([2, 1, 6, 6])

In [ ]:
a[:, :, ::2, ::2]

tensor([[[[0.8218, 0.7396, 0.8484],
          [0.8550, 0.4910, 0.1522],
          [0.0831, 0.8768, 0.7320]]],


        [[[0.6032, 0.2873, 0.7376],
          [0.6561, 0.2065, 0.3999],
          [0.0334, 0.7557, 0.8080]]],


        [[[0.4600, 0.9201, 0.8771],
          [0.0069, 0.1417, 0.2758],
          [0.4653, 0.8601, 0.3463]]],


        [[[0.8372, 0.4953, 0.2980],
          [0.0890, 0.1447, 0.6501],
          [0.7618, 0.4511, 0.6647]]]])

In [ ]:
a[:, :, ::2, ::2].shape

torch.Size([4, 1, 3, 3])

In [ ]:
e = torch.rand(3,4)
e

tensor([[0.1487, 0.3107, 0.8722, 0.0205],
        [0.4456, 0.2940, 0.4175, 0.3233],
        [0.0662, 0.9601, 0.6665, 0.1514]])

In [ ]:
e1 = e.ge(0.5)
e1

tensor([[False, False,  True, False],
        [False, False, False, False],
        [False,  True,  True, False]])

In [ ]:
torch.masked_select(e,e1)

tensor([0.8722, 0.9601, 0.6665])

In [ ]:
v = torch.rand(4,1,28,28)
v.shape

torch.Size([4, 1, 28, 28])

In [ ]:
v.view(4,28,28).shape

torch.Size([4, 28, 28])

In [ ]:
a = torch.rand(2,3)
a.shape

torch.Size([2, 3])

In [ ]:
a.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [ ]:
a.squeeze(0).shape

torch.Size([2, 3])

In [ ]:
a = torch.rand(2,3,4,5)
a.shape

torch.Size([2, 3, 4, 5])

In [ ]:
b = torch.rand(1,2,3,4)
b.shape

torch.Size([1, 2, 3, 4])

In [ ]:
b.expand(2,2,3,4).shape

torch.Size([2, 2, 3, 4])

In [ ]:
a = torch.rand(2,3)
a.shape

torch.Size([2, 3])

In [ ]:
a.t().shape

torch.Size([3, 2])

In [ ]:
a = torch.rand(2,3,4)
b = torch.rand(3,3,4)

In [ ]:
torch.cat([a,b], dim=0)

tensor([[[0.4584, 0.0222, 0.1294, 0.2042],
         [0.8889, 0.1875, 0.0933, 0.0229],
         [0.2872, 0.6610, 0.2566, 0.7033]],

        [[0.1388, 0.5973, 0.5178, 0.8129],
         [0.4763, 0.3134, 0.7248, 0.6677],
         [0.5223, 0.1695, 0.6363, 0.2396]],

        [[0.6412, 0.5550, 0.9968, 0.2728],
         [0.7351, 0.3979, 0.7749, 0.6484],
         [0.2736, 0.4453, 0.1807, 0.8580]],

        [[0.9448, 0.9539, 0.9794, 0.2104],
         [0.8217, 0.8746, 0.3552, 0.3671],
         [0.7747, 0.7907, 0.5381, 0.3254]],

        [[0.3045, 0.8051, 0.3784, 0.5264],
         [0.7541, 0.8476, 0.8285, 0.2991],
         [0.2497, 0.8494, 0.6048, 0.4095]]])

In [ ]:
torch.cat([a,b], dim=0).shape

torch.Size([5, 3, 4])

In [ ]:
c = torch.rand(2,3,4)
d = torch.rand(2,3,4)

In [ ]:
torch.stack([c,d], dim=0)

tensor([[[[0.8272, 0.2200, 0.8926, 0.6306],
          [0.9284, 0.1684, 0.6936, 0.4606],
          [0.5892, 0.1825, 0.3472, 0.1049]],

         [[0.2371, 0.0663, 0.6441, 0.6387],
          [0.2324, 0.5132, 0.8978, 0.2981],
          [0.8079, 0.8301, 0.8494, 0.3840]]],


        [[[0.0097, 0.2517, 0.8220, 0.1651],
          [0.5169, 0.4508, 0.9630, 0.8612],
          [0.5528, 0.1086, 0.9862, 0.5491]],

         [[0.4584, 0.7533, 0.1342, 0.4408],
          [0.8656, 0.3157, 0.8364, 0.1014],
          [0.8388, 0.2768, 0.4061, 0.6003]]]])

In [ ]:
torch.stack([c,d], dim=0).shape

torch.Size([2, 2, 3, 4])

In [ ]:
a = torch.rand(3,4,5)

In [ ]:
b,c = a.split([2,1], dim=0)

In [ ]:
b.shape

torch.Size([2, 4, 5])

In [ ]:
c.shape

torch.Size([1, 4, 5])

In [ ]:
a = torch.rand(5,2,3)

In [ ]:
c,d = a.chunk(2,dim=0)

In [ ]:
c.shape

torch.Size([3, 2, 3])

In [ ]:
d.shape

torch.Size([2, 2, 3])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(3)
torch.add(a,b).shape

torch.Size([2, 3])

In [ ]:
torch.rand(2,3)

tensor([[0.1028, 0.0863, 0.9842],
        [0.4956, 0.2733, 0.6007]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(3,2)

In [ ]:
torch.matmul(a,b).shape

torch.Size([2, 2])

In [ ]:
a = torch.rand(1,2,2,3)
b = torch.rand(1,2,3,2)

In [ ]:
torch.matmul(a,b).shape

torch.Size([1, 2, 2, 2])

In [4]:
np.random.randint(1,11,size=(3,10))

array([[ 1,  7,  8,  3,  9,  7,  1,  2,  9,  9],
       [ 5,  9,  2,  4,  3,  7,  1,  9,  7,  4],
       [ 1, 10,  8,  2,  9,  1,  1,  8,  6,  5]])

In [6]:
torch.ones(1,1,10).shape

torch.Size([1, 1, 10])

In [8]:
torch.zeros(1,1,5,5).shape

torch.Size([1, 1, 5, 5])