<a href="https://colab.research.google.com/github/kwwwX/git/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [16]:
a = torch.exp(torch.arange(0,20,2))

In [17]:
a.shape

torch.Size([10])

In [2]:
import numpy as np

In [4]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:
a = a.reshape(4,3,2)

In [6]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [7]:
a = torch.ones(5,3)

In [8]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
a.shape

torch.Size([5, 3])

In [3]:
a = np.array([2,3])
torch.from_numpy(a)

tensor([2, 3])

In [4]:
b = np.ones([2,3])
torch.from_numpy(b)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [5]:
c = torch.Tensor(2,3)
c

tensor([[1.1520e-34, 0.0000e+00, 3.7835e-44],
        [0.0000e+00,        nan, 0.0000e+00]])

In [6]:
torch.rand(2,3)

tensor([[0.8063, 0.1756, 0.4381],
        [0.8631, 0.6926, 0.3254]])

In [7]:
torch.randint(1,10,[2,3])

tensor([[1, 5, 2],
        [3, 9, 1]])

In [8]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
torch.full([2,3],5)

tensor([[5, 5, 5],
        [5, 5, 5]])

In [10]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [12]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [13]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
torch.eye(2,3)

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [16]:
a = torch.rand(4,1,6,6)
a[0].shape

torch.Size([1, 6, 6])

In [19]:
a[:2, : ,].shape

torch.Size([2, 1, 6, 6])

In [20]:
a[:, :, ::2, ::2]

tensor([[[[0.8218, 0.7396, 0.8484],
          [0.8550, 0.4910, 0.1522],
          [0.0831, 0.8768, 0.7320]]],


        [[[0.6032, 0.2873, 0.7376],
          [0.6561, 0.2065, 0.3999],
          [0.0334, 0.7557, 0.8080]]],


        [[[0.4600, 0.9201, 0.8771],
          [0.0069, 0.1417, 0.2758],
          [0.4653, 0.8601, 0.3463]]],


        [[[0.8372, 0.4953, 0.2980],
          [0.0890, 0.1447, 0.6501],
          [0.7618, 0.4511, 0.6647]]]])

In [21]:
a[:, :, ::2, ::2].shape

torch.Size([4, 1, 3, 3])

In [23]:
e = torch.rand(3,4)
e

tensor([[0.1487, 0.3107, 0.8722, 0.0205],
        [0.4456, 0.2940, 0.4175, 0.3233],
        [0.0662, 0.9601, 0.6665, 0.1514]])

In [25]:
e1 = e.ge(0.5)
e1

tensor([[False, False,  True, False],
        [False, False, False, False],
        [False,  True,  True, False]])

In [26]:
torch.masked_select(e,e1)

tensor([0.8722, 0.9601, 0.6665])

In [28]:
v = torch.rand(4,1,28,28)
v.shape

torch.Size([4, 1, 28, 28])

In [30]:
v.view(4,28,28).shape

torch.Size([4, 28, 28])

In [34]:
a = torch.rand(2,3)
a.shape

torch.Size([2, 3])

In [33]:
a.unsqueeze(0).shape

torch.Size([1, 2, 3])

In [38]:
a.squeeze(0).shape

torch.Size([2, 3])

In [39]:
a = torch.rand(2,3,4,5)
a.shape

torch.Size([2, 3, 4, 5])

In [40]:
b = torch.rand(1,2,3,4)
b.shape

torch.Size([1, 2, 3, 4])

In [43]:
b.expand(2,2,3,4).shape

torch.Size([2, 2, 3, 4])

In [48]:
a = torch.rand(2,3)
a.shape

torch.Size([2, 3])

In [49]:
a.t().shape

torch.Size([3, 2])